### ISSUE TITLE
Allow adding more headers on individual requests

### ISSUE THREAD

**Issue by vincentsels** [MelbourneDeveloper/RestClient.Net#13]
You can only set headers on the client, which will be executed on each request. How about also allowing to set additional headers on a per-request basis, e.g. as an optional dictionary which you can pass to each of the requests; which will be appended to the client's general headers (or replace headers in case they already exist on the client)?

**Comment by MelbourneDeveloper** [comment]
Yes, @vincentsels something like this needs to be done.

Again, I'm open to suggestions. I think you're right that there should probably be a parameter that takes a `Dictionary<string,string>` on each call. But, relating to your previous issue, headers are not always that simple. The HttpClient is actually pretty frustrating to work with and validates some headers

**Comment by MelbourneDeveloper** [comment]
@vincentsels I had a good look at this today. The unfortunate problem is that the underlying HttpClient class doesn't have this functionality. So, in order to achieve it, I'd have to shuffle the headers on to the client, and then pull them off again. That's really nasty and would end up causing all kinds of unexpected behaviour when in a multi-threaded environment. 

This comes right back to the poor design of HttpClient which is why I'm building RestClient.Net in the first place.

This won't make it in to 3.0 but as soon as there's a good solution - like finding an alternative to HttpClient, I'll implement this.

**Comment by MelbourneDeveloper** [comment]
@vincentsels I was wrong! It is possible, and I've implemented in the develop branch. V3 is very close. Thanks for your contribution!

**Comment by MelbourneDeveloper** [comment]
@vincentsels this has been included in version three which has been released on NuGet. Version three is a complete overhaul. There are samples in the unit tests.
