### ISSUE TITLE
Missing overload constructor in the client after upgrading to version 4

### ISSUE THREAD

**Issue by egarim** [MelbourneDeveloper/RestClient.Net#71]
missing overload after upgrading to version 4, before updating I was able to do this and pass the httpClientFactory

var client = new Client(new NewtonsoftSerializationAdapter(), httpClientFactory: _testServerHttpClientFactory);

after updating to version 4 this overload is missing

**Comment by MelbourneDeveloper** [comment]
@egarim actually the overload was not removed. The parameter has changed from IHttpClientFactory to a delegate called CreateHttpClient. Sorry for not communicating this well.

Here is a blog about the changes in this version:
https://christianfindlay.com/2020/06/17/restclient-net-4-0/

Importantly, this version is an attempt to allow users to inject factories with delegates instead of interfaces. Please have a read of this article: https://christianfindlay.com/2020/05/15/c-delegates-with-ioc-containers-and-dependency-injection/. It helps to decrease code while still allowing the same functionality from IHttpClientFactory. The main point is that you do not need to implement the whole interface.

All of the unit tests have been replaced with the new approach. You can still use any existing implementations of IHttpClientFactory - but they don't need to implement the interface. 

Here are some examples:

https://github.com/MelbourneDeveloper/RestClient.Net/blob/ee2f7e845b54f722e62d97250d358524946952ba/src/RestClient.Net.UnitTests/UnitTests.cs#L164

https://github.com/MelbourneDeveloper/RestClient.Net/blob/ee2f7e845b54f722e62d97250d358524946952ba/src/RestClient.Net.UnitTests/UnitTests.cs#L441

This is the most straight forward way to inject the creation of http clients in to the client:

```cs
            var client = new Client(
                baseUri: new Uri("https://restcountries.eu/rest/v2/name/australia"),
                createHttpClient: (name) => new HttpClient());
```

Please let me know if this fixes your issue.

**Comment by egarim** [comment]
Thanks, now my unit test are working again 
![UnitTest](https://user-images.githubusercontent.com/2864804/84945259-ec5a9400-b09b-11ea-8456-3b0ff8e1d1cb.png)

**Comment by MelbourneDeveloper** [comment]
@egarim great. Can I close this issue?

**Comment by egarim** [comment]
Sure close it and thanks again
