### ISSUE TITLE
Where is RestClient.Net.DependencyInjection?

### ISSUE THREAD

**Issue by CodeRedPaul** [MelbourneDeveloper/RestClient.Net#78]
Hi there

I don't quite understand... There are NuGet packages for RestClient.Net and RestClient.Net.Abstractions but NOT for RestClient.Net.DependencyInjection...!

I must be doing something wrong as it just doesn't sound feasible to have to build the binary myself and then have to worry about distro.

Can anyone shed some light, please?

Cheers,

Paul

**Comment by MelbourneDeveloper** [comment]
@CodeRedPaul sorry about this. I never ended up releasing this NuGet because it only ended up being a couple of classes. You can see them here:

https://github.com/MelbourneDeveloper/RestClient.Net/tree/main/src/RestClient.Net.DependencyInjection

The easiest thing for you would be to simply add the Microsoft NuGet packages. I think they are 

Microsoft.Extensions.Http and maybe
Microsoft.Extensions.DependencyInjection

Then, just drop the two classes above in to your project. Let me know how it goes and I may update the documentation for other people as well.
